; Regenerate IDE flags: pio run -t compiledb  -> compile_commands.json (gitignored)
[env:adafruit_feather_32u4]
platform = atmelavr
board = feather32u4
framework = arduino
monitor_speed = 115200
lib_deps = 
    arduino-libraries/SD@^1.2.4
    adafruit/Adafruit BNO055@^1.6.4
    adafruit/Adafruit BMP3XX Library@^2.1.6
